apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
