apiVersion: v1
kind: Secret
metadata:
  name: notes-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
