apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-config
  namespace: notes-app
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  APP_NAME: notes-app
  APP_ENV: production
  APP_PORT: "8000"
  LOG_LEVEL: info
